# Generated by Django 4.2.29 on 2026-04-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_labsettings_report_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinterpretation',
            name='flags_summary',
            field=models.TextField(blank=True, help_text='Summary of abnormal parameters'),
        ),
        migrations.AlterField(
            model_name='aiinterpretation',
            name='interpretation',
            field=models.TextField(blank=True, help_text='AI generated clinical interpretation text'),
        ),
        migrations.AlterField(
            model_name='analyserinterface',
            name='host',
            field=models.CharField(blank=True, help_text='IP address or COM port', max_length=200),
        ),
        migrations.AlterField(
            model_name='analyserinterface',
            name='name',
            field=models.CharField(help_text='e.g. Sysmex XN-1000, Mindray BC-5380', max_length=100),
        ),
        migrations.AlterField(
            model_name='analyserinterface',
            name='test_mapping',
            field=models.TextField(blank=True, help_text='JSON: {"MACHINE_PARAM": "TestParameter_pk"} -- maps machine codes to test params'),
        ),
        migrations.AlterField(
            model_name='analyserresult',
            name='parsed_json',
            field=models.TextField(blank=True, help_text='Parsed result as JSON'),
        ),
        migrations.AlterField(
            model_name='analyserresult',
            name='raw_data',
            field=models.TextField(help_text='Raw ASTM/HL7 message from machine'),
        ),
        migrations.AlterField(
            model_name='analyserresult',
            name='sample_id',
            field=models.CharField(help_text='Barcode / Sample ID from machine', max_length=100),
        ),
        migrations.AlterField(
            model_name='criticalvaluealert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='criticalvaluealert',
            name='notified_to',
            field=models.CharField(blank=True, help_text='Doctor/nurse name notified', max_length=200),
        ),
        migrations.AlterField(
            model_name='criticalvaluealert',
            name='notified_via',
            field=models.CharField(blank=True, help_text='Phone/WhatsApp/In-person', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorcommission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctorcommission',
            name='month',
            field=models.DateField(help_text='First day of the commission month'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hl7fhirlog',
            name='msg_type',
            field=models.CharField(choices=[('ORU_R01', 'ORU^R01 -- Lab Result'), ('ORM_O01', 'ORM^O01 -- Order'), ('ADT_A01', 'ADT^A01 -- Admission'), ('FHIR_Bundle', 'FHIR Bundle'), ('FHIR_DiagReport', 'FHIR DiagnosticReport')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hl7fhirlog',
            name='raw_message',
            field=models.TextField(blank=True, help_text='Full HL7/FHIR message payload'),
        ),
        migrations.AlterField(
            model_name='homecollection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='tpa_name',
            field=models.CharField(blank=True, help_text='Third Party Administrator name', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Reagent, Consumable, Equipment', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alert when stock falls below this level', max_digits=10),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='ai_auto_interpret',
            field=models.BooleanField(default=True, help_text='Auto-generate AI interpretation on report finalization'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='feedback_email',
            field=models.EmailField(blank=True, help_text='Email to receive feedback submissions (optional)', max_length=254),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='his_auth_token',
            field=models.CharField(blank=True, help_text='Bearer token for HIS authentication', max_length=200),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='his_endpoint_url',
            field=models.CharField(blank=True, help_text='HIS HL7 endpoint URL for sending lab results', max_length=300),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='landing_patients',
            field=models.CharField(default='5000+', help_text='Hero stat: patients served', max_length=20),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='landing_tests',
            field=models.CharField(default='200+', help_text='Hero stat: tests available', max_length=20),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='landing_years',
            field=models.CharField(default='10+', help_text='Hero stat: years experience', max_length=20),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='msg91_auth_key',
            field=models.CharField(blank=True, help_text='MSG91 Auth Key', max_length=200),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='msg91_sender_id',
            field=models.CharField(blank=True, default='IPLABS', help_text='6-char DLT Sender ID', max_length=10),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='msg91_template_id',
            field=models.CharField(blank=True, help_text='MSG91 DLT Template ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='OpenAI API key for GPT-powered interpretation (optional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_header_image',
            field=models.ImageField(blank=True, help_text='PDF Header image -- shown at top of PDF & Bulk PDF (not in direct print)', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='razorpay_key_id',
            field=models.CharField(blank=True, help_text='Razorpay Key ID (rzp_live_... or rzp_test_...)', max_length=100),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, help_text='Razorpay Key Secret', max_length=100),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='razorpay_webhook_secret',
            field=models.CharField(blank=True, help_text='Razorpay Webhook Secret', max_length=100),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='signer_image_height',
            field=models.PositiveIntegerField(default=30, help_text='Signature image height in PDF/Print (px). Controls size of uploaded signature images.'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='sms_provider',
            field=models.CharField(choices=[('none', 'Disabled'), ('msg91', 'MSG91'), ('twilio', 'Twilio')], default='none', help_text='SMS provider to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='twilio_from_number',
            field=models.CharField(blank=True, help_text='Twilio phone number e.g. +1234567890', max_length=20),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, help_text='Meta phone number ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='whatsapp_token',
            field=models.CharField(blank=True, help_text='Meta Cloud API access token', max_length=300),
        ),
        migrations.AlterField(
            model_name='mobiledevicetoken',
            name='token',
            field=models.TextField(help_text='FCM or APNs device token'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='provider_ref',
            field=models.CharField(blank=True, help_text='Provider message ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qclog',
            name='control_level',
            field=models.CharField(blank=True, help_text='e.g. Low, Normal, High', max_length=50),
        ),
        migrations.AlterField(
            model_name='qclog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qclog',
            name='instrument',
            field=models.CharField(help_text='e.g. Sysmex XN-1000, Chemistry Analyser', max_length=100),
        ),
        migrations.AlterField(
            model_name='qclog',
            name='result',
            field=models.CharField(choices=[('pass', 'Pass OK'), ('fail', 'Fail X'), ('repeat', 'Repeat needed')], default='pass', max_length=20),
        ),
        migrations.AlterField(
            model_name='qclog',
            name='test_name',
            field=models.CharField(help_text='e.g. CBC Control, Glucose QC', max_length=100),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='temperature',
            field=models.CharField(blank=True, help_text='e.g. Room temp, 4°C, Frozen', max_length=20),
        ),
        migrations.AlterField(
            model_name='testprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testprofile',
            name='name',
            field=models.CharField(help_text='e.g. Fever Profile, LFT 1.1', max_length=200),
        ),
        migrations.AlterField(
            model_name='testprofile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profile price (can be less than sum of individual tests)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='testprofile',
            name='short_code',
            field=models.CharField(blank=True, help_text='e.g. FP, LFT, KFT', max_length=20),
        ),
    ]
